version: '3.8'

services:
  recommendation-api:
    build: .
    image: hnm-recommendation-api:latest
    container_name: hnm-recommendation-api
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory
      - ./data:/app/data:ro
      # Mount model checkpoints
      - ./experiments:/app/experiments:ro
    environment:
      - DATA_DIR=/app/data
      - CHECKPOINT_DIR=/app/experiments/checkpoints
      - DEVICE=cpu  # Use cpu in Docker, change to cuda if you have nvidia-docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: hnm-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - recommendation-api
    restart: unless-stopped

  # Optional: Redis for caching
  redis:
    image: redis:alpine
    container_name: hnm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: